export const theme = {
    colors: {
      background: '#FFFFFF',
      backgroundAlt: '#F9FAFB',
      gradientPink: '#FCE7F3',
      gradientLavender: '#E0E7FF',
      black: '#000000',
      white: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#8E8E93',
      cardBg: '#F9FAFB',
      border: '#ECECEC',
      danger: '#E33',
      dangerBg: '#FDEAEA',
    },
    radii: {
      full: 999,
      xl: 28,
      lg: 20,
      md: 14,
      sm: 10,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 32,
    },
    shadow: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.04,
      shadowRadius: 30,
      elevation: 3,
    },
    shadowStrong: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 8,
    },
  }